# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170215_0849'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default=b'')),
                ('file', models.FileField(null=True, upload_to=b'')),
            ],
        ),
    ]
