# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-13 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_uploadfilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
