# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20170713_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfilemodel',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
