# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 22:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170715_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfilemodel',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='uploadfilemodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
