# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 23:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20170715_0749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadFileModel',
            new_name='ContentModel',
        ),
    ]
